//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAAService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bid_Requests_View
    {
        public int bid_num { get; set; }
        public string problem_summary { get; set; }
        public string StatusName { get; set; }
        public string Service_Location_Name { get; set; }
        public string Parent_Location_Name { get; set; }
        public System.Guid guid { get; set; }
        public string Order_Date { get; set; }
        public Nullable<System.Guid> parent_company_guid { get; set; }
        public Nullable<System.Guid> service_location_guid { get; set; }
        public bool active { get; set; }
    }
}
