//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAAService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comments_view
    {
        public string user_full_name { get; set; }
        public string Email { get; set; }
        public System.DateTime comment_datetime { get; set; }
        public string comment_type { get; set; }
        public string comments { get; set; }
        public string fileupload { get; set; }
        public string parent_location { get; set; }
        public string service_location { get; set; }
        public Nullable<bool> primary_contact_bit { get; set; }
        public Nullable<bool> is_manager { get; set; }
        public bool active { get; set; }
        public Nullable<System.DateTime> closed { get; set; }
        public string notes { get; set; }
        public System.Guid guid { get; set; }
        public int ID { get; set; }
        public Nullable<int> rating { get; set; }
        public string phone_day { get; set; }
        public string phone_night { get; set; }
        public string addr1 { get; set; }
        public string addr2 { get; set; }
    }
}
