//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAAService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailSetup
    {
        public string EmailedForm { get; set; }
        public string EmailTitle { get; set; }
        public string EmailAddress { get; set; }
        public string Host { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Port { get; set; }
        public Nullable<bool> EnableSSL { get; set; }
        public int EmailID { get; set; }
    }
}
