//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAAService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class errors_and_comments
    {
        public System.Guid guid { get; set; }
        public int ID { get; set; }
        public string HTTP_REFERER { get; set; }
        public string HTTP_USER_AGENT { get; set; }
        public string REMOTE_ADDR { get; set; }
        public string REMOTE_HOST { get; set; }
        public string REMOTE_USER { get; set; }
        public System.DateTime comment_datetime { get; set; }
        public string comment_type { get; set; }
        public System.Guid userguid { get; set; }
        public string comments { get; set; }
        public string fileupload { get; set; }
        public bool active { get; set; }
        public Nullable<System.DateTime> closed { get; set; }
        public string notes { get; set; }
        public int ratings { get; set; }
        public int RatingID { get; set; }
        public Nullable<System.Guid> LocationGUID { get; set; }
        public string LocationName { get; set; }
    
        public virtual CommentRating CommentRating { get; set; }
    }
}
