//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAAService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class error_and_comments_view
    {
        public System.Guid guid { get; set; }
        public int ID { get; set; }
        public string comments { get; set; }
        public string notes { get; set; }
        public System.DateTime comment_datetime { get; set; }
        public System.Guid userguid { get; set; }
        public bool active { get; set; }
        public int ratings { get; set; }
        public string user_full_name { get; set; }
        public string service_location { get; set; }
    }
}
