//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAAService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportToCF
    {
        public int Job_Number { get; set; }
        public string C_O_EXT { get; set; }
        public string C_T { get; set; }
        public string Job_Date { get; set; }
        public string Job_Location_Code { get; set; }
        public string Cust_Location_No { get; set; }
        public string CUST__NO_ { get; set; }
        public string JOB_LOCATION_LINE_1 { get; set; }
        public string JOB_LOCATION_LINE_2 { get; set; }
        public string JOB_LOCATION_LINE_3 { get; set; }
        public string JOB_LOCATION_LINE_4 { get; set; }
        public string JOB_REFERENCE { get; set; }
        public Nullable<int> JOB_CONTACT { get; set; }
        public string PROJECT_MANAGER { get; set; }
        public string CUSTOMER_PO_ { get; set; }
        public string SUBMITTED_AMOUNT { get; set; }
        public string C_O_Status { get; set; }
        public string STATUS_DATE { get; set; }
        public string APPROVED_AMOUNT { get; set; }
        public string ESTIMATED_TAX_INCLUDED { get; set; }
        public string ESTIMATED_TAX_ADDITIONAL { get; set; }
        public string RET_ { get; set; }
        public string TAX_STATE { get; set; }
        public string COUNTY { get; set; }
        public string SALES_REP { get; set; }
        public string Sales_Tax { get; set; }
        public string Labor_Tax { get; set; }
        public string Use_Tax { get; set; }
        public string Condense_Costs { get; set; }
        public string Job_Complete { get; set; }
        public string Alt_G_L_ { get; set; }
        public string Std_Phs_Cat { get; set; }
        public string Markups { get; set; }
        public string SORT_DATE { get; set; }
        public string JOB_START_DATE { get; set; }
        public string JOB_END_DATE { get; set; }
        public string USER_DEFINED_1 { get; set; }
        public string USER_DEFINED_2 { get; set; }
        public string USER_DEFINED_3 { get; set; }
        public string USER_DEFINED_4 { get; set; }
    }
}
