//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAAService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationEmails_viewMVC1
    {
        public string LocationName { get; set; }
        public string UserEmail { get; set; }
        public System.Guid LocationGUID { get; set; }
        public Nullable<bool> email_all_members { get; set; }
        public int account_status { get; set; }
    }
}
