//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAAService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location_Mgt_ViewMVC
    {
        public string name { get; set; }
        public string addressline1 { get; set; }
        public string addressline2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public int zip { get; set; }
        public string cf_location_num { get; set; }
        public string cf_company_num { get; set; }
        public string region { get; set; }
        public Nullable<System.Guid> parentguid { get; set; }
        public System.Guid guid { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string full_name { get; set; }
        public Nullable<System.Guid> user_guid { get; set; }
        public string phone_day { get; set; }
        public string phone_night { get; set; }
        public string parent_name { get; set; }
        public Nullable<bool> primary_contact_bit { get; set; }
    }
}
