//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAAService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location_Service_Provider
    {
        public System.Guid guid { get; set; }
        public System.Guid location_guid { get; set; }
        public System.Guid service_category_guid { get; set; }
        public System.Guid service_provider_guid { get; set; }
        public bool active { get; set; }
        public System.DateTime date_in { get; set; }
        public System.DateTime last_modified { get; set; }
        public System.Guid last_modified_by { get; set; }
        public Nullable<System.Guid> location_specific_notes { get; set; }
    
        public virtual locationinfo locationinfo { get; set; }
    }
}
