//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAAService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportBuilder_View
    {
        public Nullable<int> age { get; set; }
        public string service_location_name { get; set; }
        public int job_number { get; set; }
        public System.DateTime order_datetime { get; set; }
        public Nullable<int> PriorityID { get; set; }
        public string problem_summary { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string company_name { get; set; }
        public Nullable<System.Guid> service_location_guid { get; set; }
        public Nullable<System.Guid> parent_company_guid { get; set; }
        public System.Guid guid { get; set; }
        public Nullable<System.DateTime> complete_datetime { get; set; }
        public string region { get; set; }
        public string category { get; set; }
        public string service_provider { get; set; }
        public string city { get; set; }
        public Nullable<System.DateTime> dispatch_datetime { get; set; }
        public Nullable<System.DateTime> accepted_datetime { get; set; }
        public string internal_notes { get; set; }
        public string notes { get; set; }
        public string problem_details { get; set; }
        public string equipment_model { get; set; }
        public string equipment_serial_number { get; set; }
        public string equipment_problem_description { get; set; }
        public string cost_code { get; set; }
        public string total_billing { get; set; }
        public string requested_by { get; set; }
    }
}
