//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAAService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class service_tickets_viewMVC
    {
        public string Created_By_User_fname { get; set; }
        public string Created_By_User_lname { get; set; }
        public int job_number { get; set; }
        public System.DateTime order_datetime { get; set; }
        public System.DateTime last_update_datetime { get; set; }
        public string PriorityStatus { get; set; }
        public string problem_summary { get; set; }
        public string problem_details { get; set; }
        public string location_contact_name { get; set; }
        public string location_contact_phone { get; set; }
        public string StatusName { get; set; }
        public string Updated_By_User_fname { get; set; }
        public string Updated_By_User_Lname { get; set; }
        public string Parent_Location_Name { get; set; }
        public string Parent_Location_AddressLine1 { get; set; }
        public string Parent_Location_AddressLine2 { get; set; }
        public string Parent_Location_City { get; set; }
        public string Parent_Location_State { get; set; }
        public int Parent_Location_Zip { get; set; }
        public System.Guid guid { get; set; }
        public string Order_Time { get; set; }
        public string Order_Date { get; set; }
        public Nullable<System.DateTime> complete_datetime { get; set; }
        public string notes { get; set; }
        public string cf_company_num { get; set; }
        public string cf_location_num { get; set; }
        public Nullable<System.DateTime> closed_datetime { get; set; }
        public string location_contact_phone_night { get; set; }
        public string category { get; set; }
        public string Service_Location_Name { get; set; }
        public string Service_Location_Addressline1 { get; set; }
        public string Service_Location_AddressLine2 { get; set; }
        public string Service_Location_City { get; set; }
        public string Service_Location_State { get; set; }
        public Nullable<int> Service_Location_Zip { get; set; }
        public string cost_code { get; set; }
        public string EQmodel { get; set; }
        public string EQserial { get; set; }
        public string EQProbDesc { get; set; }
        public string service_provider { get; set; }
        public Nullable<System.DateTime> dispatch_datetime { get; set; }
        public Nullable<System.DateTime> accepted_datetime { get; set; }
        public string internal_notes { get; set; }
        public System.Guid parent_company_guid { get; set; }
        public System.Guid service_location_guid { get; set; }
        public string cust_po_num { get; set; }
        public string category_value { get; set; }
        public string total_billing { get; set; }
    }
}
