//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAAService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class service_ticket_files
    {
        public System.Guid guid { get; set; }
        public string file_name { get; set; }
        public int file_size { get; set; }
        public string file_ext { get; set; }
        public System.Guid user_guid { get; set; }
        public System.Guid ticket_guid { get; set; }
        public System.DateTime date_in { get; set; }
        public bool active { get; set; }
    
        public virtual service_tickets service_tickets { get; set; }
    }
}
