//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAAService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site_Lists_Hide_Item
    {
        public System.Guid guid { get; set; }
        public System.Guid parent_company_guid { get; set; }
        public System.Guid list_item_guid { get; set; }
        public System.DateTime date_in { get; set; }
    }
}
