//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AAAService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Info_ViewMVC
    {
        public string company_name { get; set; }
        public string acct_status { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string email { get; set; }
        public string location_name { get; set; }
        public System.Guid user_guid { get; set; }
        public string phone_day { get; set; }
        public string phone_night { get; set; }
        public Nullable<System.Guid> location_guid { get; set; }
        public Nullable<System.Guid> parent_location_guid { get; set; }
        public Nullable<int> account_status { get; set; }
    }
}
